// Autogenerated by the TAPAAL (www.tapaal.net)

/*
 EF Target=1 
*/
E<> ((Token0.Target + Token1.Target + Token2.Target + Token3.Target + Token4.Target + Token5.Target)== 1) && ((Token0.P_lock + Token1.P_lock + Token2.P_lock + Token3.P_lock + Token4.P_lock + Token5.P_lock) == 1)
